import React, { useState } from 'react';
import { Download, Film, Settings, Play } from 'lucide-react';
import { useProject } from '../context/ProjectContext';

export const Header: React.FC = () => {
  const { clips, texts, transitions, audioTracks, settings } = useProject();
  const [isExporting, setIsExporting] = useState(false);

  const handleExport = () => {
    setIsExporting(true);
    // Simulate export process
    setTimeout(() => {
      const config = {
        clips,
        texts,
        transitions,
        audioTracks,
        settings
      };
      
      const blob = new Blob([JSON.stringify(config, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'project_config.json';
      a.click();
      URL.revokeObjectURL(url);
      
      setIsExporting(false);
      alert('Project configuration exported! You can use this JSON with the Python rendering pipeline.');
    }, 1500);
  };

  const handleRender = () => {
    setIsExporting(true);
    // Simulate rendering process
    setTimeout(() => {
      setIsExporting(false);
      
      // Create a dummy video file blob to simulate the download
      const content = "This is a simulated video file. In a full production environment, this would be a compiled MP4 generated by FFmpeg or a cloud rendering backend.";
      const blob = new Blob([content], { type: 'video/mp4' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'rendered_video.mp4';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
    }, 3000);
  };

  return (
    <header className="h-14 bg-[#1a1a1a] border-b border-[#333] flex items-center justify-between px-4 text-white shrink-0">
      <div className="flex items-center gap-2">
        <div className="w-8 h-8 bg-blue-600 rounded flex items-center justify-center">
          <Film size={18} />
        </div>
        <h1 className="font-semibold text-lg tracking-tight">VideoStitch Pro</h1>
      </div>
      
      <div className="flex items-center gap-3">
        <button 
          onClick={() => setSelection({ type: 'project', id: null })}
          className="p-2 hover:bg-[#333] rounded-md transition-colors text-gray-400 hover:text-white"
          title="Project Settings"
        >
          <Settings size={18} />
        </button>
        <button 
          onClick={handleExport}
          className="flex items-center gap-2 bg-[#333] hover:bg-[#444] text-white px-4 py-1.5 rounded-md text-sm font-medium transition-colors"
        >
          <Download size={16} />
          Export JSON
        </button>
        <button 
          onClick={handleRender}
          disabled={isExporting}
          className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 disabled:bg-blue-800 text-white px-4 py-1.5 rounded-md text-sm font-medium transition-colors"
        >
          {isExporting ? (
            <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
          ) : (
            <Play size={16} />
          )}
          {isExporting ? 'Rendering...' : 'Render Video'}
        </button>
      </div>
    </header>
  );
};
